{
 "title": "Refresh Status",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Status History",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "[[tag_CheckName]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "CheckName::tag" ], "type": "tag" }
     ],
     "measurement": "refresh_status",
     "query": "SELECT last(\"StatusType\") FROM \"autogen\".\"refresh\" WHERE $timeFilter GROUP BY time($interval), \"CheckName\"::tag, \"Description\"::tag ORDER BY time DESC",
     "select": [
      [
       { "params": [ "StatusType" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "[[tag_CheckName]]",
     "groupBy": [
      { "params": [ "CheckName::tag" ], "type": "tag" }
     ],
     "measurement": "refresh_status",
     "select": [
      [
       { "params": [ "StatusType" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Totals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Total Levels",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "refresh_statistics",
     "select": [
      [
       { "params": [ "totalLevels" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total Photos",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "refresh_statistics",
     "select": [
      [
       { "params": [ "totalPhotos" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total Users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "refresh_statistics",
     "select": [
      [
       { "params": [ "totalUsers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Levels",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "levels" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "refresh_statistics",
     "select": [
      [
       { "params": [ "totalLevels" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "people" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "refresh_statistics",
     "select": [
      [
       { "params": [ "totalUsers" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Photos",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "photos" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "refresh_statistics",
     "select": [
      [
       { "params": [ "totalPhotos" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Rooms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rooms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Rooms",
     "measurement": "refresh_statistics",
     "select": [
      [
       { "params": [ "currentRoomCount" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current In-game Player Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "players" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Rooms",
     "measurement": "refresh_statistics",
     "select": [
      [
       { "params": [ "currentIngamePlayersCount" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "Api Requests/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "refresh_statistics",
     "select": [
      [
       { "params": [ "requestStatistics_apiRequests" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "Game Requests/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "refresh_statistics",
     "select": [
      [
       { "params": [ "requestStatistics_gameRequests" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "Legacy API Requests/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "refresh_statistics",
     "select": [
      [
       {
        "params": [
         "requestStatistics_legacyApiRequests"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests/s",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "refresh_statistics",
     "select": [
      [
       {
        "params": [
         "requestStatistics_totalRequests"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  }
 ]
}